apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  labels:
    app: task-api
spec:
  revisionHistoryLimit: 2 # Keep only previous 2 revisions (replica sets)
  replicas: 2
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: task-weightage-api:v1.0
          imagePullPolicy: Always # Crucial: tells K8s to always pull using the local registry
          ports:
            - containerPort: 8000

          # 1. Resource Boundaries
          resources:
            requests:
              cpu: "100m"      # 1/10th of a core
              memory: "128Mi"  # Guaranteed memory
            limits:
              cpu: "250m"      # Max CPU allowed
              memory: "256Mi"  # K8s will kill the pod if it exceeds this

          # 2. Liveness Probe (Restarts the pod if it hangs)
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5  # Give the app 5s to boot before checking
            periodSeconds: 15       # Check every 15s
            timeoutSeconds: 2       # If no response in 2s, it fails
            failureThreshold: 3     # Restart pod after 3 consecutive failures

          # 3. Readiness Probe (Stops traffic routing if it's busy/starting)
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1     # Needs 1 success to start receiving traffic

          # PostgreSQL connection specific variables
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Must match the metadata.name in your secret YAML
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres-service" # Kubernetes translates this automatically
---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  type: NodePort # Opens a port on the VMs so Windows can access it
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080