apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-deployment
  labels:
    app: task-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: task-weightage-api:v1.0
          imagePullPolicy: Always # Crucial: tells K8s to always pull using the local registry
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials  # Must match the metadata.name in your secret YAML
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres-service"
---
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
spec:
  type: NodePort # Opens a port on the VMs so Windows can access it
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080